### ISSUE TITLE
installation doesn't work with thor 0.11.5

### ISSUE THREAD

**Issue by jberkel** [emmapersky/one-click-orgs#35]
```
   /Library/Ruby/Gems/1.8/gems/thor-0.11.5/bin/../lib/thor.rb:140:in `initialize': wrong number of arguments (3 for 0) (ArgumentError)
from /Library/Ruby/Gems/1.8/gems/thor-0.11.5/bin/../lib/thor.rb:140:in `new'
```

**Comment by jberkel** [comment]
http://osdir.com/ml/merb/2009-08/msg00025.html

**Comment by chrismear** [comment]
Merb issue.
