### ISSUE TITLE
Error when sending welcome email from closing a successful 'new member' proposal

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#86]
When a 'new member' proposal is closed via Proposal.close_proposals, and the proposal succeeds, sending the welcome emails fails with this bug:

```
irb(main):005:0> Proposal.close_proposals
ActiveRecord::RecordNotFound: Couldn't find Member without an ID
        from /home/oneclickorgs/.bundle/ruby/1.8/gems/activerecord-3.0.0.beta/lib/active_record/relation/finder_methods.rb:250:in `find_with_ids'
        from /home/oneclickorgs/.bundle/ruby/1.8/gems/activerecord-3.0.0.beta/lib/active_record/relation/finder_methods.rb:99:in `find'
        from /home/oneclickorgs/.bundle/ruby/1.8/gems/activerecord-3.0.0.beta/lib/active_record/base.rb:560:in `__send__'
        from /home/oneclickorgs/.bundle/ruby/1.8/gems/activerecord-3.0.0.beta/lib/active_record/base.rb:560:in `find'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/member.rb:84:in `send_new_member_email'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/member.rb:80:in `send_welcome'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/member.rb:73:in `create_member'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/add_member_proposal.rb:3:in `enact!'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/proposal.rb:100:in `close!'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/proposal.rb:118:in `close_early_proposals'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/proposal.rb:118:in `each'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/proposal.rb:118:in `close_early_proposals'
        from /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/models/proposal.rb:124:in `close_proposals'
        from (irb):5
```

**Comment by jberkel** [comment]
Save member, send then email. Closed by 050f8ada5e6bd0b3857603defc5928caefc3c1aa.
